Bangazon/urls.py
from django.urls import path
from . import views

app_name = 'Bangazon'
urlpatterns = [
    path('Bangazon/Employees', views.employees, name='employees'),
    path('Bangazon/Employees/<int:employee_id>', views.employee_details, name='employee_details'),
    path('Bangazon/Employees/form', views.employee_form, name='employee_form'),
    path('Bangazon/Employees/new', views.employee_new, name='employee_new'),
    path('Bangazon/Employees/<int:pk>/edit', views.employee_edit, name='employee_edit'),
    path('Bangazon/Employees/<int:pk>/update', views.employee_update, name='employee_update'),
    # path('Bangazon/Employees/update', views.employee_update, name='employee_update'),

    path('Bangazon/Departments', views.departments, name='departments'),
    path('Bangazon/Departments/NewDepartment', views.new_department, name='new_department'),
    path('Bangazon/Departments/SaveDepartment', views.save_department, name='save_department'),
    path('Bangazon/Departments/<int:department_id>', views.department_details, name='department_details'),
    path('Bangazon/Departments/<int:department_id>/EditDepartment', views.department_edit, name='department_edit'),
    path('Bangazon/Departments/<int:department_id>/update', views.department_update, name='department_update'),

# ==================Computers==================================================
    path('Bangazon/Computers', views.computers, name='computers'),
    path('Bangazon/Computers/<int:computer_id>', views.computer_details, name='computer_details'),
    path('Bangazon/Computers/new', views.computer_new, name='computer_new'),
    path('Bangazon/Computers/form', views.computer_form, name='computer_form'),
    path('Bangazon/Computers/delete_confirm', views.computer_delete_confirm, name='computer_delete_confirm'),
    path('Bangazon/Computers/delete', views.computer_delete, name='computer_delete'),
    path('Bangazon/Computers/decommission', views.computer_decommision, name='computer_decommision'),
# ===============================================================================================


    path('Bangazon', views.landing_page, name='landing_page'),
    path('Bangazon/Training', views.training_programs, name='training_programs'),
    path('Bangazon/Training/<int:trainingprogram_id>/', views.training_details, name='training_details'),
    path('Bangazon/Training/Past/<int:trainingprogram_id>/', views.past_training_details, name='past_training_details'),
    path('Bangazon/Training/PastTraining', views.past_training_programs, name='past_training_programs'),
    path('Bangazon/Training/NewTrainingClass', views.new_training_program_form, name='new_training_program_form'),
    path('Bangazon/Training/SaveProgram', views.save_program, name='save_program'),
    path('Bangazon/Training/EditTraining/<int:trainingprogram_id>/', views.edit_training_details, name='edit_training_details'),
    path('Bangazon/Training/UpdateProgram', views.update_program, name='update_program'),
    path('Bangazon/Training/DeleteProgram', views.training_delete, name='training_delete'),
]

Bangazon1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Bangazon.urls'))

]

Bangazon/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator



# Create Department table
class Department(models.Model):
    '''This is the representation of an instance of Department. A department has a name (a string) and budget (an interger) and an id.
    
    Author(s): Brad Davis, Jase Hackman, Zac Jones, Nolan Little, Austin Zoradi
    '''
    budget = models.IntegerField(
    default = 0,
    validators = [
      MaxValueValidator(1000000),
      MinValueValidator(0)
    ]
  )
    name = models.CharField(max_length = 50)
    def __str__(self):
        return self

# Create Computer table
class Computer(models.Model):
    """Create computers in the database with the needed fields

        Model:Its self

        Template: all of the computer templates



        Author(s): Jase Hackman, Brad Davis
        """


    purchaseDate = models.DateTimeField()
    decommissionDate = models.DateTimeField(null=True)
    manufacturer = models.CharField(max_length = 50)
    model = models.CharField(max_length = 50)
    def __str__(self):
        return self.model

# Create Employee table
class Employee(models.Model):
    firstName = models.CharField(max_length = 50)
    lastName = models.CharField(max_length = 50)
    startDate = models.DateTimeField()
    isSupervisor = models.IntegerField(
    default = 0,
    validators = [
        MaxValueValidator(1),
        MinValueValidator(0)
    ]
    )
    computer = models.ManyToManyField(Computer, through="Employee_Computer")
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    def __str__(self):
        return self.firstName




# Create Training Course table
class TrainingProgram(models.Model):
    """Creates Training Program Class and sets parameters

    Model: Itself

    Template: A Bunch

    Author(s): Brad Davis
    """
    name = models.CharField(max_length = 50)
    description = models.CharField(max_length = 250)
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    maxEnrollment = models.IntegerField(
        default = 0,
        validators = [
        MaxValueValidator(100),
        MinValueValidator(0)
        ]
    )
    employee = models.ManyToManyField(Employee, through="EmployeeTrainingProgram")
    def __str__(self):
        return self

class Employee_Computer(models.Model):

    """Creates join table between Employees and Computers

        Model: Employees and Computers

        Template: all of the computer templates



        Author(s): Jase Hackman, Brad Davis
        """

    employee=models.ForeignKey('Employee', on_delete=models.CASCADE)
    computer=models.ForeignKey('Computer', on_delete=models.CASCADE)
    assignDate=models.DateTimeField()
    removeDate=models.DateTimeField(null=True)

# Create Training Enrollment join table
class EmployeeTrainingProgram(models.Model):
    """Creates relationship between employee and training program

    Model: Itself, Employee, TrainingProgram

    Template: A bunch

    Author(s): Jase Hackman, Brad Davis
    """
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE)
    trainingProgram = models.ForeignKey('TrainingProgram', on_delete=models.CASCADE)
    status = models.CharField(max_length = 50)
    def __str__(self):
        return self

Bangazon/views.py
from django.shortcuts import render,  get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from .models import *
import math
from .forms import *
import datetime
import pytz
from django.db.models import Q


# ======================== Landing Page ================


def landing_page(request):
    """Renders main landing page for Bangazon

    Model:None

    Template:index.html

    Author(s): Brad Davis
    """
    return render(request, 'Bangazon/index.html')


# ======================== EMPLOYEES ================


def employees(request):
    """Lists all employees in the database

    Model:Employee

    Template:employees.html

    Author(s): Zac Jones
    """

    employee_list = Employee.objects.all().order_by('lastName')
    context = {'employee_list': employee_list}
    return render(request, 'Bangazon/employees.html', context)


def employee_details(request, employee_id):
    """view method for an employee's details

    model(s): Employee, Computer, TrainingProgram

    template: employee_details.html

    Arguments:
        request {httprequest}
        employee_id {int} -- id of employee reversed from url path

    Returns:
        render -- html with the employee_details, past_training_programs, and upcoming_training_programs as context

    Author(s): Nolan Little
    """

    now = timezone.now()
    employee_details = Employee.objects.get(pk=employee_id)
    past_training_programs = list()
    upcoming_training_programs = list()
    for program in employee_details.trainingprogram_set.all():
        if (program.startDate < now):
            past_training_programs.append(program)
        elif (program.startDate > now):
            upcoming_training_programs.append(program)
    context = {
        'employee_details': employee_details,
        'past_training_programs': past_training_programs,
        'upcoming_training_programs': upcoming_training_programs
    }
    return render(request, 'Bangazon/employee_details.html', context)


def employee_form(request):
    """Calls new employee form, populates dropdown with list of departments

    Model:Employee, Department

    Template:employee_form.html

    Author(s): Zac Jones
    """

    departments = Department.objects.all()
    context = {"departments": departments}
    return render(request, "Bangazon/employees_form.html", context)


def employee_new(request):
    """Saves a new instance of Employee via POST to the db, redirects to the list of all instances of employee

    Model:Employee, Department

    Template: redirects back to employees.html

    Author(s): Zac Jones
    """

    department = Department.objects.get(pk=request.POST['department'])
    employee = Employee(firstName = request.POST['firstName'], lastName = request.POST['lastName'], startDate = request.POST['startDate'], isSupervisor = request.POST['supervisor'], department = department)

    employee.save()
    return HttpResponseRedirect(reverse('Bangazon:employees'))


def employee_update(request, pk):
    """Saves an edited instance of Employee via POST to the db, redirects to the list of all instances of employee

    Model:Employee, Department, Computers, Training

    Template: redirects back to employees.html

    Author(s): Zac Jones, Nolan Little
    """

    department = Department.objects.get(pk=request.POST['department'])
    employee_edited = Employee(id=pk, firstName = request.POST['firstName'], lastName = request.POST['lastName'], startDate = request.POST['startDate'], isSupervisor = request.POST['supervisor'], department = department)

    employee_edited.save()
    return HttpResponseRedirect(reverse('Bangazon:employees'))


def employee_edit(request, pk):
    """Saves a new instance department via POST to the db, redirects to the list of all instances of department

    Model:Employee, Department, Computers, Training

    Template: redirects back to departments.html

    * Module is currently incomplete - still needs training assignments fix *

    Author(s): Zac Jones, Nolan Little
    """

    employee = get_object_or_404(Employee, id=pk)
    now = timezone.now()

    all_computers = Computer.objects.filter(decommissionDate = None)
    comp_relationships = Employee_Computer.objects.filter(removeDate= None)
    comp_list = list()
    # appends to comp_list only computers that are currently in commission and are not assigned to an employee
    for unassigned_comp in comp_relationships:
        for computer in all_computers:
            if unassigned_comp.id == computer.id:
                comp_list.append((computer.id, f'{computer.manufacturer} {computer.model}'))
    # inserts the employees currently assigned employee to the dropdown
    if len(employee.computer.all()) > 0:
        current_computer = employee.computer.all()[0]
        comp_list.insert(0, (current_computer.id, f'{current_computer.manufacturer} {current_computer.model}'))
        initial_comp_id = current_computer.id
    else:
        initial_comp_id = 0


    comp_list.insert(0, (0, 'None Assigned'))


    dept_list = list()
    departments = Department.objects.all()
    for department in departments:
        dept = (department.id, department.name)
        dept_list.append(dept)

    train_list = list()
    training_program_list = TrainingProgram.objects.filter(startDate__gte=now)
    for program in training_program_list:
        train_list.append((program.id, f'{program.name} \n beginning:{program.startDate}'))


    current_enrollment = list()
    for program in employee.trainingprogram_set.all():
        current_enrollment.append(program.id)


    # convert list of choice tuples into a tuple for passing to form class
    computer_list = tuple(comp_list)
    department_list = tuple(dept_list)
    training_list = tuple(train_list)

    department = Department.objects.get(employee=pk)
    form = EmployeeEditForm(dept_choices = department_list,
                            comp_choices = computer_list,
                            train_choices = training_list,
                            initial={
                                'firstName': employee.firstName,
                                'lastName': employee.lastName,
                                'Start Date': employee.startDate,
                                'supervisor': employee.isSupervisor,
                                'department': department.id,
                                'computer': initial_comp_id,
                                'training': current_enrollment
                                }
                            )
    return render(request, 'Bangazon/employee_edit.html', {'form': form, 'employee': employee})


# ========================DEPARTMENTS================


def departments(request):
    """Returns a list of all departments

    Model:Department

    Template:departments.html

    Author(s): Austin Zoradi
    """

    department_list = Department.objects.all().order_by('name')
    context = {'department_list': department_list}
    return render(request, 'Bangazon/departments.html', context)


def new_department(request):
    """Generates a form to add a new department to the db

    Model:Department

    Template:new_department_form.html

    Author(s): Austin Zoradi
    """
    department_list = Department.objects.all()
    context = {'department_list': department_list}
    return render(request, 'Bangazon/new_department_form.html', context)


def save_department(request):
    """Saves a new instance department via POST to the db, redirects to the list of all instances of department

    Model:Department

    Template: redirects back to departments.html

    Author(s): Austin Zoradi
    """
    name = request.POST['department_name']
    budget = request.POST['department_budget']
    handleIntBudget = int(str(budget).split(".")[0])
    dep = Department(name=name, budget=handleIntBudget)
    dep.save()
    return HttpResponseRedirect(reverse('Bangazon:departments'))


def department_details(request, department_id):
    """Returns a list of the details of an instance of a single department and the employee instances associated with it

    Model:Department

    Template:departments_details.html

    Author(s): Austin Zoradi
    """
    department_details = Department.objects.get(pk=department_id)
    context = {'department_details': department_details}
    return render(request, 'Bangazon/department_details.html', context)

def department_edit(request, department_id):
    """Returns an edit form prepopulated with data of the department that is going to be edited

    Arguments: department_id {[pk]} -- id of the department that is to be edited

    Model:Department

    Template:edit_department_form.html
    """
    department = Department.objects.get(id=department_id)
    context = {"department": department}
    return render(request, 'Bangazon/edit_department_form.html', context)

def department_update(request, department_id):
    """Updates the instance of department with id department_id with the new input values from the form in the db, rerenders department list

    Arguments: department_id {[pk]} -- id of the department that is to be edited

    Model:Department

    Template:edit_department_form.html
    """
    budget=request.POST['department_budget']
    handleIntBudget = int(str(budget).split(".")[0])
    edited_dept = Department(id=department_id, name=request.POST['department_name'], budget=handleIntBudget)
    edited_dept.save()
    return HttpResponseRedirect(reverse('Bangazon:departments'))

# ==========================COMPUTERS=================================


def computers(request):
    """Calls in main computer page and has function for filters

    Model:Computer

    Template:computers.html

    Author(s): Jase Hackman, Nolen Little, Austin Zoradi
    """
    if request.POST:

Bangazon/templates/Bangazon/computer_delete_confirm.html
<!-- Basic block for computers -->
{% extends "Bangazon/index.html" %}

{% block content %}

<div class="delete_div">
    <h1 class="main_title">Delete Computer</h1>
    {% if assigned == True %}
    <p>Computer is assigned to an employee and cannot be deleted.<p>
            <button class="btn btn_margin"><a href="{% url 'Bangazon:computer_details' computer.id %}">Back</a></button>

            {% else %}
            <p>Are you sure you want to delete {{computer.model}}?</p>
            <form method="post" action="{% url 'Bangazon:computer_delete'%}">
                {% csrf_token %}
                <input type="hidden" value="{{computer.id}}" name="computer_id">
                <button class="btn btn_margin"><a href="{% url 'Bangazon:computer_details' computer.id %}">No</a></button>
                <input type="submit" class="btn" value="Delete">
                </from>
                {% endif %}

</div>

{% endblock content %}

Bangazon/templates/Bangazon/computer_details.html
<!-- Basic block for computers -->
{% extends "Bangazon/index.html" %}

{% block content %}

<div id="main_container detail_div">
    <h1 class="main_title">{{computer.model}}</h1>
    <ul>
      <li>
        Manufacturer: {{computer.manufacturer}}
      </li>
      <li>
        Model: {{computer.model}}
      </li>
      <li>
        Purchase Date: {{computer.purchaseDate}}
      </li>
      {% if computer.employee_computer_set.all|length == 0 and computer.decommissionDate == None %}
        <form method='post' action="{% url 'Bangazon:computer_decommision' %}">
            {% csrf_token %}
            <input type="hidden" name="computer_id" value="{{computer.id}}">
            <input type="submit" value="Decommission">
        </form>
        {% elif computer.decommissionDate != None %}

        <li>
            Decommission Date: {{computer.decommissionDate}}
        </li>
        {% elif relationships|length > 0 and None not in relationships %}
        <form method='post' action="{% url 'Bangazon:computer_decommision' %}">
            {% csrf_token %}
            <input type="hidden" name="computer_id" value="{{computer.id}}">
            <input type="submit" value="Decommission">
        </form>

      {% endif %}
        {% if computer.employee_computer_set.all|length > 0 %}
         {% for rel in computer.employee_computer_set.all %}
            {% if rel.removeDate == NULL %}
                <li>
                    Assigned To: {{rel.employee.firstName}} {{rel.employee.lastName}}
                </li>
            {% else %}
                <li>
                    Past Assignment: {{rel.employee.firstName}} {{rel.employee.lastName}}
                </li>
            {% endif %}
        {% endfor %}
        {% endif %}
    </ul>
    <div class="computer_btns">

        <form method="post" action="{% url 'Bangazon:computer_delete_confirm' %}">
            {% csrf_token %}
            <input type="hidden" value="{{computer.id}}" name="computer_id">
            <input type="submit" class="btn btn-primary" value="Delete">
        </form>
        <button class="btn btn_margin btn-primary"><a href="{% url 'Bangazon:computers' %}">Back</a></button>
    </div>

</div>

{% endblock content %}

Bangazon/templates/Bangazon/computers.html
<!-- Basic block for computers -->
{% extends "Bangazon/index.html" %}

{% block content %}

  <div id="main_container">
    <h1 class="main_title">Computers</h1>
    <button class="btn btn_margin btn-primary"><a href="{% url 'Bangazon:computers' %}">View All Computers</a></button>
    <button class="btn btn_margin btn-primary"><a href ="{% url 'Bangazon:computer_form' %}">Add Computer</a></button>
    {% if computer_list %}
        <form class="filter_form" action="{% url 'Bangazon:computers' %}" method="POST">
            {% csrf_token %}
            <p>Filter Computers By Make or Manufacturer</p>
            <input placeholder="make or manufacturer" type="text" name="computer_search" id="computer_search">
            <input type="submit" value="Search" class="btn btn-primary">
        </form>
      <ul class="list-group list-group-flush dept_list">
        {% for computer in computer_list %}
        <li class="list-group-item">
          <a href="{% url 'Bangazon:computer_details' computer.id %}">Make:{{computer.manufacturer}} --Model: {{computer.model}}</a>
            {% for employeerel in computer.employee_computer_set.all %}
                {% if employeerel.removeDate == NULL %}
                 {% for employee in computer.employee_set.all %}
                    {% if employeerel.employee_id == employee.id %}
                        <p>Assigned To: {{employee.firstName}} {{employee.lastName}}</p>
                    {% endif %}
                {% endfor %}
                {% endif %}
            {% endfor %}
        </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="no_items_found">No computers in system.</p>
    {% endif %}
  </div>

{% endblock content %}

Bangazon/templates/Bangazon/department_details.html
{% extends "Bangazon/index.html" %}
{% load humanize %}

{% block content %}

{% if department_details %}
<h1 class="main_title">{{department_details.name}} Department Details</h1>
<div class="detail_div">

    <p>Budget: ${{department_details.budget|intcomma}}</p>
    <P>Employees:</P>
    <ul>
        {% for emp in department_details.employee_set.all %}
        <li> {{emp.firstName}} {{emp.lastName}} </li>
        {% endfor %}
    </ul>

    {% else %}
    <p class="no_items_found">No Employees in this Department.</p>
    {% endif %}
    <button class="btn btn-primary btn_margin"><a href="{% url 'Bangazon:departments' %}">See All Departments</a></button>
    <button class="btn btn-primary btn_margin"><a href="{% url 'Bangazon:department_edit' department_details.id %} ">Edit Department</a></button>
</div>

{% endblock content %}

Bangazon/templates/Bangazon/departments.html
<!-- Basic block for departments -->
{% extends "Bangazon/index.html" %}
{% load humanize %}

{% block content %}
<h1 class="main_title">Departments</h1>
<div class="add_department">
    <button class="btn btn_margin btn-primary"><a class="no_dec" href="{% url 'Bangazon:new_department' %}">Add a New Department</a></button>
</div>
<section class="department_list">
    <div>
        {% if department_list %}
        <ul class="list-group list-group-flush dept_list">
            <p>{{department_list.employee_set}}</p>
            {% for department in department_list %}
            <li class="list-group-item">
                <p><a href="{% url 'Bangazon:department_details' department.id %}">{{department.name}} </a> </p>
                <p>Budget: ${{department.budget|intcomma}} </p>
                <p> Number of Employees:
                    {{ department.employee_set.all|length}} </p>
            </li>
            {% endfor %}
            
        </ul>
        {% else %}
        <p class="no_items_found">No departments in system.</p>
        {% endif %}
    </div>
</section>


{% endblock content %}

Bangazon/templates/Bangazon/employee_details.html
{% extends "Bangazon/index.html" %}

{% block content %}

<div id="main_container">
    <h1 class="main_title">Employee Details</h1>
    {% if employee_details %}
    <ul class="bangazon_list">
        <h3>{{employee_details.firstName}} {{employee_details.lastName}}</h3>
        <h4>{% if employee_details.isSupervisor == 1 %}--Department Supervisor{% endif %}</h4>
        <ul>
            <li class="bangazon_list_item">Hire Date: {{employee_details.startDate}}</li>
            <li class="bangazon_list_item">Department:{{employee_details.department.name}}</li>

            {% if employee_details.computer.all|length == 0 %}
            <li class="bangazon_list_item">Computer: No computer assigned.
                {% endif %}

                {% for computer in employee_details.computer.all %}
                <a href={% url 'Bangazon:computer_details' computer.id %}>
            <li>Computer: {{computer.manufacturer}} {{computer.model}} , ID#: {{computer.id}}</li></a>
            {% endfor %}
        </ul>
        <h4>Upcoming Training Enrollment</h4>
        <ul>
            {% if upcoming_training_programs|length > 0 %}
            {% for program in upcoming_training_programs %}
            <li class="bangazon_list_item">{{program.name}} beginning: {{program.startDate}}</li>
            {% endfor %}
            {% else %}
            <li class="bangazon_list_item">No upcoming enrollments</li>
            {% endif %}
        </ul>
        <h4>Completed Training Enrollment</h4>
        <ul>
            {% if past_training_programs|length > 0 %}
            {% for program in past_training_programs %}
            <li class="bangazon_list_item">{{program.name}} beginning: {{program.startDate}}</li>
            {% endfor %}
            {% else %}
            <li class="bangazon_list_item">No completed training programs</li>
            {% endif %}
        </ul>

        <button class="btn btn_margin btn-primary"><a href="{% url 'Bangazon:employee_edit' employee_details.id %}">Edit Employee</a></button>


        {% else %}
        <p class="no_items_found">No employees in system.</p>
        {% endif %}
</div>

{% endblock content %}

Bangazon/templates/Bangazon/indiv_training_program.html
<!-- Basic block for  individual training program-->
{% extends "Bangazon/index.html" %}

{% block content %}

<div id="main_container">
    <h1 class="main_title">Training Programs</h1>
    {% if training_program_details %}
    <section class="bangazon_list_item detail_div">
        <p class="training_title">{{training_program_details.name}}</p>
        <p class="training_description">Description: {{training_program_details.description}}</p>
        <p class="training_start">Start Date: {{training_program_details.startDate}}</p>
        <p class="training_end">End Date: {{training_program_details.endDate}}</p>
        <p class="training_max">Max Enrollment: {{training_program_details.maxEnrollment}}</p>
        <p class="training_max">Attendees: </p>
        {% if attendees %}
        {% for person in attendees %}
        <p class="indiv_trainee">{{person.firstName}} {{person.lastName}}</p>
        {% endfor %}
        {% else %}
        <p class="indiv_no_trainee">No trainees assigned.</p>
        {% endif %}
    </section>
    <section class="computer_btns">
        <button class="btn btn_margin btn-primary"><a class="past_link" href="{% url 'Bangazon:edit_training_details' training_program_details.id %}">
                Edit Training Details
            </a></button>
        <form class="past_link" action="{% url 'Bangazon:training_delete' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{training_program_details.id}}" name="trainingprogram_id">
            <input class="btn btn-primary" type="submit" value="Delete Training Class">
        </form>
    </section>
    {% endif %}
</div>

{% endblock content %}

Bangazon/templates/Bangazon/nav.html
<!-- Basic block for navbar -->
{% block nav %}
<nav class="=navbar navbar-expand-lg navbar-light bg-light nav_flex">

    <ul class="navbar-nav nav_flex">
        <li>
            <a class="navbar-brand" href="{% url 'Bangazon:landing_page' %}">Bangazon</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Bangazon:employees' %}">Employees</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Bangazon:departments' %}">Departments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Bangazon:computers' %}">Computers</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Bangazon:training_programs' %}">Training Programs</a>
        </li>
    </ul>
    </div>

</nav>

{% endblock %}

Bangazon/templates/Bangazon/new_training_program_form.html
<!-- Basic block for  individual training program-->
{% extends "Bangazon/index.html" %}

{% block content %}

<div id="main_container">
    <h1 class="main_title">Create New Training Program</h1>
    <form class="training_form" action="{% url 'Bangazon:save_program' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="form_button" type="submit" value="Save Training">
    </form>
    <section class="training_nav_button">
        <button class="btn btn_margin btn-primary"> <a class="past_link" href="{% url 'Bangazon:training_programs' %}">
                View Upcoming Classes
            </a></button>
    </section>
</div>

{% endblock content %}

Bangazon/templates/Bangazon/new_training_program_form_error.html
<!-- Basic block for  individual training program-->
{% extends "Bangazon/index.html" %}

{% block content %}

<div id="main_container">
  <h1 class="main_title">Create New Training Program</h1>
  <h1 class="error_alert">The End Date for the class must be after the Start Date.</h1>
  <form class="add_training" action="{% url 'Bangazon:save_program' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input class="btn btn-primary" type="submit" value="Save Training">
  </form>
  <section class="training_nav_button">
    <a class="past_link" href="{% url 'Bangazon:training_programs' %}">
      <p class="past_program_btn">View Upcoming Classes</p>
    </a>
  </section>
</div>

{% endblock content %}

Bangazon/templates/Bangazon/training_program.html
<!-- Basic block for training -->
{% extends "Bangazon/index.html" %}

{% block content %}

<div id="main_container">
    <h1 class="main_title">Training Programs</h1>
    <section class="training_nav_buttons">
        <button class="btn btn_margin btn-primary"><a class="past_link" href="{% url 'Bangazon:new_training_program_form' %}">
                Add Training Class
            </a></button>

    </section>
    {% if training_program_list %}
    <ul class="list-group list-group-flush dept_list">
        {% for program in training_program_list %}
        <li class="list-group-item">
            <a class="training_name_list" href="{% url 'Bangazon:training_details' program.id %}">
                <p class="program_name">{{ program.name }}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p class="no_items_found">No future training programs in system.</p>
    {% endif %}
    <section class="training_nav_buttons">
        <button class="btn btn_margin btn-primary">
            <a class="past_link" href="{% url 'Bangazon:past_training_programs' %}">
                Past Training Classes</a>
        </button>
    </section>

</div>

{% endblock content %}